# Generated by Django 4.2.6 on 2023-10-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandeCLUB', '0003_commande_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoueurDeChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandeCLUB.taille')),
            ],
        ),
    ]
