# Generated by Django 4.2.6 on 2023-10-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandeCLUB', '0004_joueurdechamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='couleurs',
        ),
        migrations.RemoveField(
            model_name='article',
            name='personnalisable',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tailles',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='personnalisation',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='couleur',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='joueurdechamp',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='joueurdechamp',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='type_utilisateur',
        ),
        migrations.AddField(
            model_name='club',
            name='utilise_hoodie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='club',
            name='utilise_maillot_domicile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='club',
            name='utilise_maillot_visiteur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='couleur',
            name='couleur_nom',
            field=models.CharField(default='Default Color', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calibre',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibres', to='commandeCLUB.club'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='calibre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_calibre', to='commandeCLUB.calibre'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='commandeCLUB.club'),
        ),
        migrations.AlterField(
            model_name='taille',
            name='taille',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='commandeCLUB.club'),
        ),
    ]
