# Generated by Django 4.2.6 on 2023-10-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandeCLUB', '0005_remove_article_couleurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurdechamp',
            name='chaussettes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaussettes', to='commandeCLUB.article'),
        ),
        migrations.AddField(
            model_name='joueurdechamp',
            name='maillot_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maillots_locaux', to='commandeCLUB.article'),
        ),
        migrations.AddField(
            model_name='joueurdechamp',
            name='maillot_visiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maillots_visiteurs', to='commandeCLUB.article'),
        ),
        migrations.AddField(
            model_name='joueurdechamp',
            name='short',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='commandeCLUB.article'),
        ),
        migrations.AddField(
            model_name='joueurdechamp',
            name='taille_chaussettes',
            field=models.CharField(choices=[('35-38', '35-38'), ('39-42', '39-42'), ('43-47', '43-47')], default='39-42', max_length=5),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='PersonnelDEntrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandeCLUB.club')),
                ('hoodie_couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoodie_couleur', to='commandeCLUB.couleur')),
                ('hoodie_taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoodie_taille', to='commandeCLUB.taille')),
                ('polo_couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polo_couleur', to='commandeCLUB.couleur')),
                ('polo_taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polo_taille', to='commandeCLUB.taille')),
                ('short_couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_short_couleur', to='commandeCLUB.couleur')),
                ('short_taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_short_taille', to='commandeCLUB.taille')),
            ],
        ),
        migrations.CreateModel(
            name='Gardien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('maillot_type_manche', models.CharField(choices=[('court', 'Court'), ('long', 'Long')], max_length=50)),
                ('chaussette_couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardien_chaussette_couleur', to='commandeCLUB.couleur')),
                ('chaussette_taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardien_chaussette_taille', to='commandeCLUB.taille')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandeCLUB.club')),
                ('maillot_couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardien_maillot_couleur', to='commandeCLUB.couleur')),
                ('maillot_taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardien_maillot_taille', to='commandeCLUB.taille')),
                ('short_couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardien_short_couleur', to='commandeCLUB.couleur')),
                ('short_taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardien_short_taille', to='commandeCLUB.taille')),
            ],
        ),
    ]
