# Generated by Django 4.2.6 on 2023-10-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandeCLUB', '0007_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibre',
            name='has_chaussettes_local',
            field=models.BooleanField(default=True, verbose_name='Utilise chaussettes local'),
        ),
        migrations.AddField(
            model_name='calibre',
            name='has_maillot_local',
            field=models.BooleanField(default=True, verbose_name='Utilise maillot local'),
        ),
        migrations.AddField(
            model_name='calibre',
            name='has_maillot_visiteur',
            field=models.BooleanField(default=False, verbose_name='Utilise maillot visiteur'),
        ),
        migrations.AddField(
            model_name='calibre',
            name='has_short_local',
            field=models.BooleanField(default=True, verbose_name='Utilise short local'),
        ),
        migrations.AddField(
            model_name='calibre',
            name='has_short_visiteur',
            field=models.BooleanField(default=False, verbose_name='Utilise short visiteur'),
        ),
    ]
